export const REALTIME_EVENTS = {
  TRANSACTION_CREATED: 'transaction:created',
  TRANSACTION_CANCELLED: 'transaction:cancelled',
  TRANSACTION_REFUNDED: 'transaction:refunded',
  PRODUCT_CREATED: 'product:created',
  PRODUCT_UPDATED: 'product:updated',
  PRODUCT_TOPPING_UPDATED: 'product:toppingUpdated',
  PRODUCT_CATEGORY_CREATED: 'product:categoryCreated',
  STORE_UPDATED: 'store:updated',
  STORE_BANK_UPDATED: 'store:bankUpdated',
  STORE_RECEIPT_UPDATED: 'store:receiptUpdated',
};

export const TRANSACTION_REFRESH_EVENTS = [
  REALTIME_EVENTS.TRANSACTION_CREATED,
  REALTIME_EVENTS.TRANSACTION_CANCELLED,
  REALTIME_EVENTS.TRANSACTION_REFUNDED,
];

export const PRODUCT_REFRESH_EVENTS = [
  REALTIME_EVENTS.PRODUCT_CREATED,
  REALTIME_EVENTS.PRODUCT_UPDATED,
  REALTIME_EVENTS.PRODUCT_TOPPING_UPDATED,
  REALTIME_EVENTS.PRODUCT_CATEGORY_CREATED,
];
